from typing import Literal
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from core.state import TutorState

# ---------------------------------------------------------
# 1. Define the Structured Output Schema
# ---------------------------------------------------------
class RefereeVerdict(BaseModel):
    """Schema for the strict evaluation of the user's submission."""
    status: Literal["PASS", "FAIL", "PARTIAL", "SYSTEM_ERROR"] = Field(
        description="The final evaluation status. Use SYSTEM_ERROR if the puzzle logic is flawed."
    )
    score: float = Field(
        description="A confidence or accuracy score between 0.0 and 1.0.",
        ge=0.0, le=1.0
    )
    technical_feedback: str = Field(
        description="Objective, cold technical feedback for the Coach to translate (e.g., 'Syntax error on line 4')."
    )
    conceptual_block_detected: bool = Field(
        description="True if the user is making the exact same error repeatedly."
    )

# ---------------------------------------------------------
# 2. Configure the LLM
# ---------------------------------------------------------
# We use a high-reasoning model (temperature=0) to ensure deterministic grading.
# In production, this is an excellent place to swap in a fine-tuned reasoning model.
llm = ChatOpenAI(model="gpt-4o", temperature=0.0)
structured_referee = llm.with_structured_output(RefereeVerdict)

system_prompt = """You are the Referee Agent. Your ONLY role is adversarial verification.
You will be provided with:
1. The 'Answer Key' generated by the game engine.
2. The 'User Submission' containing their attempt to solve it.

Your tasks:
- Compare the submission strictly against the answer key.
- Evaluate the logic, not just the exact string match.
- Be objective and clinical. You are a Scantron machine, not a teacher.
- If the generated Answer Key itself is impossible or logically flawed, return 'SYSTEM_ERROR'.

Do NOT speak to the user. Output ONLY the evaluation payload for the Coach Agent."""

referee_prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("user", "Answer Key Context:\n{answer_key}\n\nUser Submission:\n{submission}")
])

# Create the LangChain chain
referee_chain = referee_prompt | structured_referee

# ---------------------------------------------------------
# 3. The LangGraph Node Function
# ---------------------------------------------------------
def referee_node(state: TutorState):
    """
    Evaluates the user's interactive response against the game's logic,
    updates the verdict, and passes the baton to the Coach.
    """
    print("--- [AGENT ACTIVE] Referee ---")
    
    # 1. Extract the ground truth and the user's answer
    game_state = state.get("game_state", {})
    answer_key = game_state.get("game_logic", "No logic found.")
    
    # The user's last message is their submission
    user_submission = state["messages"][-1].content
    
    # 2. Invoke the Critic logic
    verdict: RefereeVerdict = referee_chain.invoke({
        "answer_key": answer_key,
        "submission": user_submission
    })
    
    print(f"--- [REFEREE VERDICT] {verdict.status} (Score: {verdict.score}) ---")
    
    # 3. Handle the "Exit/Abandon" logic discussed previously
    # If a conceptual block is detected or score is 0 too many times, 
    # we flag the state so the Path Planner / Coach can force a pivot.
    if verdict.conceptual_block_detected:
        print("--- [WARNING] Conceptual block detected. Triggering pivot. ---")
        
    # 4. Package the State Update
    # The baton ALWAYS passes to the Coach so the feedback is buffered.
    return {
        "active_agent": "referee",
        "referee_verdict": verdict.model_dump_json(),
        "next_action": "deliver_feedback"
    }